### ISSUE TITLE
Installation takes 3 hours...

### ISSUE THREAD

**Issue by philipdenys** [shawnabramson/magento2-install#3]

**Comment by philipdenys** [comment]
is this normal? How long does it take for you guys?

**Comment by shawnabramson** [comment]
Hi @philipdenys sorry, I just saw this. Not sure why I didn't get notified. If it takes 3 hours, its probably some issue on your machine itself or possibly your Docker settings. 

A full install without sample data takes 10-15 mins and with sample data takes about 30 mins.

I just released version 2.0 of the script about 20 minutes ago. Its a bit smarter and more efficient. You might want to give it a try.
