### ISSUE TITLE
Ran into "PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted"

### ISSUE THREAD

**Issue by SamCritch** [shawnabramson/magento2-install#4]
I ran into this error due to a memory limitation on CLI-based PHP on my Mac when running composer. Fixed it with this environment variable on the front of the install script:

`COMPOSER_MEMORY_LIMIT=-1 magento2-install`

**Comment by shawnabramson** [comment]
Thanks @SamCritch . If I receive multiple reports of this occurring I may add it to the script. Also, please feel free to submit a PR that incorporates that into the script.

**Comment by shawnabramson** [comment]
@SamCritch I just added your suggestion to the script. Good call on that one and thank you!

**Comment by SamCritch** [comment]
> @SamCritch I just added your suggestion to the script. Good call on that one and thank you!

Ah, great to hear @shawnabramson - thanks for that!
