### ISSUE TITLE
MariaDB 10.5 and Magento 2.4.1

### ISSUE THREAD

**Issue by andreyan-andreev** [shawnabramson/magento2-install#5]
Hey there I have tried your script, but it is currently failing when it tries to install magento. The issues boils down to the fact that mariadb has pushed new version to docker hub, and that version is not supported by magento.

```
In SqlVersionProvider.php line 93:

  Current version of RDBMS is not supported. Used Version: 10.5.8-MariaDB-1:10.5.8+maria~focal. Supported versions: MySQL-8, MySQL-5.7, MariaDB-(10.2-10.4)
```

I have tried to replace the db version in your script
```
DEFAULT_DOCKER_DB_IMAGE=mariadb:10
```
with 10.2 also 10.4, but then i hit this error:

```
Waiting for Docker database container to be fully up and running...
Docker database container took too long to initialize. Exiting...
```

db container gets into restart limbo
```
mysql_1          | 2021-01-07 11:15:01 0 [ERROR] Unknown/unsupported storage engine: InnoDB
mysql_1          | 2021-01-07 11:15:01 0 [ERROR] Aborting
```

**Comment by shawnabramson** [comment]
Hi @andreyan-andreev thanks for bringing this to my attention. I will make this fix tonight but if you find a solution sooner please open a PR. Thank you!

**Comment by andreyan-andreev** [comment]
Hey thanks for attending this. Actually i gave it another shot today, but first removed all docker volumes that were created during my numerous attempts and this turns out to be the solution. So in brief the script appears to work ok, and the only change needed is:

```
DEFAULT_DOCKER_DB_IMAGE=mariadb:10
```
replace with:
```
DEFAULT_DOCKER_DB_IMAGE=mariadb:10.4
```

**Comment by shawnabramson** [comment]
Excellent, thank you! I am committing this change now to make it an official part of the script. Any version of Magento less than 2.4 will use Mariadb 10.2 and >= 2.4 will use Mariadb 10.4

**Comment by shawnabramson** [comment]
@andreyan-andreev  The changes have now been pushed. Thanks again for bringing this to my attention!
